#!/bin/bash

function uxcat {
	if [ -n "$1" ]; then
		if [ ! -p $1 -a -n "$(file -L $1 | cut -d':' -f2 | grep bzip2)" ]; then
			bzcat $1
		elif [ ! -p $1 -a -n "$(file -L $1 | cut -d':' -f2 | grep gzip)" ]; then
			zcat $1
		else
			cat $1
		fi
	else
		cat
	fi
}

for f in $@; do uxcat $f; done
